# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coworkersimpaqto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coworker',
            name='username',
            field=models.CharField(blank=True, max_length=16, verbose_name='Usuario'),
        ),
    ]
