# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-11 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coworkersimpaqto', '0002_coworker_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
