# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-22 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coworkersimpaqto', '0004_auto_20160222_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumo',
            name='fecha_entrada',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='consumo',
            name='fecha_salida',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
